name: Build NestJS

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Build NestJS using package.json
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout application code
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@master
              with:
                node-version: 18
                cache: "npm"
            - name: Install dependencies    
              run: npm install
            - name: Build application
              run: npm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with: 
                name: build-artifact
                path: dist