name: Build NestJS

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Build NestJS using package.json
        runs-on: ununtu-latest
        steps: 
            - name: Checkout application code
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@master
              with:
                node-version: 18
            - name: 2 commands
              run: |
                echo "Hello github action"
                echo "We do a 13 lesson"
            - name: Install dependencies    
              run: npm install
            - name: Build application
              run: npm run build