name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 942c7a43-b70b-49c2-9b0c-12053475e484
          heroku_app_name: "github-cicd-lesson"
          heroku_email: "blackjneco@gmail.com"
          usedocker: true